<?php

/**
 * @file
 * Primary module hooks for Global Tokens module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function global_tokens_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_token module.
    case 'help.page.global_tokens':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('How to use token text goes here.') . '</p>';
      return $output;

    default:
  }
}
